import type { LevelConfig, YamlLine } from './types';

function y(text: string, highlight?: 'violation' | 'ok' | 'neutral'): YamlLine {
  return highlight ? { text, highlight } : { text };
}

export const LEVELS: LevelConfig[] = [
  // ─── Level 1: No Privileged Containers ───────────────────────────────────
  {
    id: 1,
    title: 'No Privileged Containers',
    policyName: 'POLICY-001: Privilege Escalation Ban',
    intro:
      'Corporate security has one rule: no container runs with elevated host privileges. ' +
      'privileged: true bypasses all Linux security mechanisms and gives containers near-root access to the host kernel. ' +
      'Admit pods that comply. Deny any pod where a container sets privileged: true.',
    rules: [
      {
        id: 'no-privileged',
        label: 'No privileged: true',
        description: 'No container (including init containers) may set securityContext.privileged: true.',
      },
    ],
    timeLimit: 120,
    pointsPerCorrect: 100,
    scenarios: [
      {
        id: 'l1-s1',
        podName: 'nginx-web',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'No securityContext means privileged defaults to false. This container cannot touch host devices, load kernel modules, or access /proc of other processes. Safe to admit.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: nginx-web'),
          y('    image: nginx:1.21-alpine'),
          y('    ports:'),
          y('    - containerPort: 80'),
        ],
      },
      {
        id: 'l1-s2',
        podName: 'debug-shell',
        namespace: 'ops',
        verdict: 'deny',
        violatedRule: 'no-privileged',
        explanation: 'A privileged container can mount the host filesystem, read /proc of every process on the node including the kubelet\'s service account token, and load kernel modules. A single container breakout becomes full node compromise.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: debug-shell'),
          y('    image: ubuntu:22.04'),
          y('    securityContext:'),
          y('      privileged: true', 'violation'),
          y('      runAsUser: 0', 'violation'),
        ],
      },
      {
        id: 'l1-s3',
        podName: 'api-server',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'privileged: false is explicit. Combined with runAsNonRoot and allowPrivilegeEscalation: false, a compromise of this container stays contained — no path to the host kernel.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: api-server'),
          y('    image: gcr.io/myco/api:v2.3.1'),
          y('    securityContext:'),
          y('      privileged: false', 'ok'),
          y('      runAsNonRoot: true', 'ok'),
          y('      allowPrivilegeEscalation: false', 'ok'),
        ],
      },
      {
        id: 'l1-s4',
        podName: 'build-agent',
        namespace: 'ci',
        verdict: 'deny',
        violatedRule: 'no-privileged',
        explanation: 'Init containers run before your app and can stage an attack. This init-setup container with privileged: true has full host access during pod startup — long enough to exfiltrate secrets or plant a backdoor before the main container even starts.',
        yaml: [
          y('spec:'),
          y('  initContainers:'),
          y('  - name: init-setup'),
          y('    image: busybox:1.36'),
          y('    securityContext:'),
          y('      privileged: true', 'violation'),
          y('  containers:'),
          y('  - name: build-agent'),
          y('    image: gcr.io/myco/builder:3.1'),
        ],
      },
      {
        id: 'l1-s5',
        podName: 'redis-cache',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'No privileged field means it defaults to false. The explicit allowPrivilegeEscalation: false and readOnlyRootFilesystem: true further limit what an attacker can do if this container is compromised.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: redis'),
          y('    image: redis:7.0-alpine'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      readOnlyRootFilesystem: true', 'ok'),
          y('      runAsUser: 999', 'ok'),
        ],
      },
      {
        id: 'l1-s6',
        podName: 'node-monitor',
        namespace: 'monitoring',
        verdict: 'deny',
        violatedRule: 'no-privileged',
        explanation: 'Monitoring agents are a high-value target precisely because they\'re often over-privileged. A compromised node-exporter with privileged: true is not a metrics scraper — it\'s a full node backdoor. Use specific capabilities like SYS_PTRACE for /proc reads instead.',
        yaml: [
          y('spec:'),
          y('  hostNetwork: true', 'neutral'),
          y('  containers:'),
          y('  - name: node-exporter'),
          y('    image: prom/node-exporter:v1.7'),
          y('    securityContext:'),
          y('      privileged: true', 'violation'),
        ],
      },
      {
        id: 'l1-s7',
        podName: 'app-worker',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'Non-root user (UID 1000) with a read-only root filesystem. Even if this container is compromised, the attacker is a low-privilege user who cannot modify the container filesystem or access host interfaces.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: worker'),
          y('    image: python:3.11-slim'),
          y('    securityContext:'),
          y('      runAsUser: 1000', 'ok'),
          y('      runAsGroup: 1000', 'ok'),
          y('      readOnlyRootFilesystem: true', 'ok'),
        ],
      },
      {
        id: 'l1-s8',
        podName: 'mesh-proxy',
        namespace: 'production',
        verdict: 'deny',
        violatedRule: 'no-privileged',
        explanation: 'The sidecar is the attack surface here. A compromised envoy proxy with privileged: true can dump secrets from other pods\' /proc memory maps, rewrite iptables rules to intercept traffic, and pivot to the underlying node.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/myco/app:v1.4'),
          y('  - name: envoy-sidecar'),
          y('    image: envoyproxy/envoy:v1.27'),
          y('    securityContext:'),
          y('      privileged: true', 'violation'),
        ],
      },
    ],
  },

  // ─── Level 2: No Host Namespaces ─────────────────────────────────────────
  {
    id: 2,
    title: 'No Host Namespaces',
    policyName: 'POLICY-002: Host Namespace Isolation',
    intro:
      'Pods that share host namespaces can see every process, IPC resource, or network interface on the node. ' +
      'Deny any pod that sets hostPID, hostIPC, or hostNetwork to true.',
    rules: [
      {
        id: 'no-host-pid',
        label: 'No hostPID: true',
        description: 'Pods may not share the host PID namespace.',
      },
      {
        id: 'no-host-ipc',
        label: 'No hostIPC: true',
        description: 'Pods may not share the host IPC namespace.',
      },
      {
        id: 'no-host-network',
        label: 'No hostNetwork: true',
        description: 'Pods may not use the host network stack.',
      },
    ],
    timeLimit: 110,
    pointsPerCorrect: 110,
    scenarios: [
      {
        id: 'l2-s1',
        podName: 'webserver',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'No host namespace fields set — all default to false. This pod lives entirely in its own isolated network, PID, and IPC namespaces.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: web'),
          y('    image: nginx:1.21'),
          y('    ports:'),
          y('    - containerPort: 8080'),
        ],
      },
      {
        id: 'l2-s2',
        podName: 'process-inspector',
        namespace: 'ops',
        verdict: 'deny',
        violatedRule: 'no-host-pid',
        explanation: 'hostPID: true means the container can see every process on the node — the kubelet, the container runtime, and other pods. An attacker can signal those processes, read /proc/fd symlinks to steal open file descriptors, and dump credentials from process memory.',
        yaml: [
          y('spec:'),
          y('  hostPID: true', 'violation'),
          y('  containers:'),
          y('  - name: inspector'),
          y('    image: gcr.io/tools/inspector:v1'),
        ],
      },
      {
        id: 'l2-s3',
        podName: 'net-monitor',
        namespace: 'monitoring',
        verdict: 'deny',
        violatedRule: 'no-host-network',
        explanation: 'hostNetwork: true removes all network isolation. This pod can listen on any host port, intercept unencrypted traffic between node-local processes, and bypass NetworkPolicy entirely — policies are enforced at the pod network level, not the host.',
        yaml: [
          y('spec:'),
          y('  hostNetwork: true', 'violation'),
          y('  containers:'),
          y('  - name: monitor'),
          y('    image: gcr.io/tools/netmon:v2'),
          y('    ports:'),
          y('    - containerPort: 9090'),
        ],
      },
      {
        id: 'l2-s4',
        podName: 'database',
        namespace: 'data',
        verdict: 'admit',
        explanation: 'All three host namespace fields explicitly set to false. The pod is fully isolated: cannot see host PIDs, cannot access host IPC segments, cannot bind host network interfaces.',
        yaml: [
          y('spec:'),
          y('  hostPID: false', 'ok'),
          y('  hostIPC: false', 'ok'),
          y('  hostNetwork: false', 'ok'),
          y('  containers:'),
          y('  - name: postgres'),
          y('    image: postgres:15'),
        ],
      },
      {
        id: 'l2-s5',
        podName: 'ipc-bridge',
        namespace: 'internal',
        verdict: 'deny',
        violatedRule: 'no-host-ipc',
        explanation: 'hostIPC: true lets the container attach to any shared memory segment on the node. Other pods or system services that use POSIX shared memory are now readable and writable from inside this container.',
        yaml: [
          y('spec:'),
          y('  hostIPC: true', 'violation'),
          y('  containers:'),
          y('  - name: bridge'),
          y('    image: gcr.io/internal/ipc-bridge:v1'),
        ],
      },
      {
        id: 'l2-s6',
        podName: 'metrics-agent',
        namespace: 'monitoring',
        verdict: 'admit',
        explanation: 'No host namespaces, no privileged mode. The runAsNonRoot and allowPrivilegeEscalation: false in the security context further limit blast radius.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: agent'),
          y('    image: gcr.io/metrics/agent:v3.2'),
          y('    securityContext:'),
          y('      runAsNonRoot: true', 'ok'),
          y('      allowPrivilegeEscalation: false', 'ok'),
        ],
      },
      {
        id: 'l2-s7',
        podName: 'node-agent',
        namespace: 'kube-system',
        verdict: 'deny',
        violatedRule: 'no-host-pid',
        explanation: 'Two violations: hostPID exposes all node processes; hostNetwork removes pod-level network isolation. Either alone is a deny. Together they give an attacker the tools to map, intercept, and pivot across the entire node.',
        yaml: [
          y('spec:'),
          y('  hostPID: true', 'violation'),
          y('  hostNetwork: true', 'violation'),
          y('  containers:'),
          y('  - name: agent'),
          y('    image: gcr.io/security/agent:v1'),
        ],
      },
      {
        id: 'l2-s8',
        podName: 'sidecar-app',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'Multi-container pod with no host namespace access. The sidecar\'s readOnlyRootFilesystem: true prevents it from being used as a staging ground if compromised.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/myco/app:v2.0'),
          y('  - name: sidecar'),
          y('    image: gcr.io/myco/sidecar:v1.1'),
          y('    securityContext:'),
          y('      readOnlyRootFilesystem: true', 'ok'),
        ],
      },
    ],
  },

  // ─── Level 3: Run As Non-Root ─────────────────────────────────────────────
  {
    id: 3,
    title: 'Run As Non-Root',
    policyName: 'POLICY-003: Non-Root Enforcement',
    intro:
      'Containers running as root (UID 0) can cause serious damage if they escape the container. ' +
      'Every container must either set runAsNonRoot: true or specify a non-zero runAsUser. ' +
      'No security context at all means the container might run as root — deny it.',
    rules: [
      {
        id: 'run-as-non-root',
        label: 'Non-root required',
        description: 'All containers must set runAsNonRoot: true OR runAsUser > 0. No security context = deny.',
      },
    ],
    timeLimit: 110,
    pointsPerCorrect: 120,
    scenarios: [
      {
        id: 'l3-s1',
        podName: 'web-app',
        namespace: 'production',
        verdict: 'deny',
        violatedRule: 'run-as-non-root',
        explanation: 'No securityContext means this container might run as root (UID 0). A root process in a container that escapes — via a kernel exploit or container runtime bug — has the same privileges on the host as the root user. Non-root enforcement is your first containment layer.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: web'),
          y('    image: nginx:1.21'),
          y('    ports:'),
          y('    - containerPort: 80'),
        ],
      },
      {
        id: 'l3-s2',
        podName: 'api-service',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'Pod-level runAsNonRoot: true with runAsUser: 1000 applies to all containers. The effective UID is 1000 — not root. A container escape drops the attacker into an unprivileged user context on the host.',
        yaml: [
          y('spec:'),
          y('  securityContext:'),
          y('    runAsNonRoot: true', 'ok'),
          y('    runAsUser: 1000', 'ok'),
          y('    runAsGroup: 1000', 'ok'),
          y('  containers:'),
          y('  - name: api'),
          y('    image: gcr.io/myco/api:v3.1'),
        ],
      },
      {
        id: 'l3-s3',
        podName: 'legacy-db',
        namespace: 'data',
        verdict: 'deny',
        violatedRule: 'run-as-non-root',
        explanation: 'runAsUser: 0 is explicit root. Any process in this container runs with UID 0. If it escapes the container boundary, it has root-level access to the host filesystem, other pods\' files, and system binaries.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: db'),
          y('    image: mysql:8.0'),
          y('    securityContext:'),
          y('      runAsUser: 0', 'violation'),
        ],
      },
      {
        id: 'l3-s4',
        podName: 'worker',
        namespace: 'jobs',
        verdict: 'admit',
        explanation: 'runAsUser: 999 with runAsGroup: 999 — the container runs as an unprivileged system user. Limits post-escape damage to what UID 999 can access on the host.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: worker'),
          y('    image: gcr.io/myco/worker:v2.0'),
          y('    securityContext:'),
          y('      runAsUser: 999', 'ok'),
          y('      runAsGroup: 999', 'ok'),
        ],
      },
      {
        id: 'l3-s5',
        podName: 'multi-svc',
        namespace: 'production',
        verdict: 'deny',
        violatedRule: 'run-as-non-root',
        explanation: 'The main app is correctly configured but the sidecar has no user set. Admission policy applies to every container. An attacker who compromises the sidecar gets a root process unless all containers define a non-root user.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/myco/app:v1'),
          y('    securityContext:'),
          y('      runAsUser: 1000', 'ok'),
          y('  - name: sidecar'),
          y('    image: gcr.io/myco/sidecar:v1'),
          y('    # no securityContext', 'violation'),
        ],
      },
      {
        id: 'l3-s6',
        podName: 'scanner',
        namespace: 'security',
        verdict: 'admit',
        explanation: 'Pod-level runAsNonRoot: true covers both containers. The individual container securityContexts reinforce it with explicit UIDs. Defense in depth — multiple layers enforcing the same constraint.',
        yaml: [
          y('spec:'),
          y('  securityContext:'),
          y('    runAsNonRoot: true', 'ok'),
          y('  containers:'),
          y('  - name: scanner'),
          y('    image: gcr.io/sec/scanner:v4'),
          y('    securityContext:'),
          y('      runAsUser: 500', 'ok'),
          y('  - name: reporter'),
          y('    image: gcr.io/sec/reporter:v2'),
          y('    securityContext:'),
          y('      runAsNonRoot: true', 'ok'),
        ],
      },
      {
        id: 'l3-s7',
        podName: 'init-as-root',
        namespace: 'staging',
        verdict: 'deny',
        violatedRule: 'run-as-non-root',
        explanation: 'Init containers run first and can be the weakest link. This init-db container runs as root (UID 0) during the database migration phase — plenty of time to write to host paths or steal credentials before the main app starts.',
        yaml: [
          y('spec:'),
          y('  initContainers:'),
          y('  - name: init-db'),
          y('    image: busybox:1.36'),
          y('    securityContext:'),
          y('      runAsUser: 0', 'violation'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/myco/app:v1'),
          y('    securityContext:'),
          y('      runAsUser: 1000', 'ok'),
        ],
      },
      {
        id: 'l3-s8',
        podName: 'nobody-svc',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'UID 65534 is the traditional \'nobody\' user — no meaningful permissions on the host. runAsNonRoot: true adds runtime enforcement on top of the UID. Well hardened.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: service'),
          y('    image: gcr.io/myco/service:v1.2'),
          y('    securityContext:'),
          y('      runAsNonRoot: true', 'ok'),
          y('      runAsUser: 65534', 'ok'),
          y('      runAsGroup: 65534', 'ok'),
        ],
      },
    ],
  },

  // ─── Level 4: Capability Restrictions ────────────────────────────────────
  {
    id: 4,
    title: 'Drop All Capabilities',
    policyName: 'POLICY-004: Capability Lockdown',
    intro:
      'Linux capabilities carve up root privileges into discrete units. ' +
      'The policy is strict: all containers must drop ALL default capabilities. ' +
      'The only permitted re-addition is NET_BIND_SERVICE (for binding to ports < 1024). ' +
      'No drop:ALL means deny. Any other add means deny.',
    rules: [
      {
        id: 'drop-all',
        label: 'Must drop ALL',
        description: 'Every container must include capabilities.drop: [ALL].',
      },
      {
        id: 'no-dangerous-caps',
        label: 'Only NET_BIND_SERVICE allowed',
        description: 'Containers may only add NET_BIND_SERVICE. All other capability adds are denied.',
      },
    ],
    timeLimit: 100,
    pointsPerCorrect: 130,
    scenarios: [
      {
        id: 'l4-s1',
        podName: 'web-server',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'Drops all default Linux capabilities and adds none. The container starts with the absolute minimum — no CHOWN, no DAC_OVERRIDE, no SETUID. If compromised, the attacker cannot leverage any capability to escape or escalate.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: web'),
          y('    image: gcr.io/myco/web:v1'),
          y('    securityContext:'),
          y('      capabilities:'),
          y('        drop:', 'ok'),
          y('        - ALL', 'ok'),
        ],
      },
      {
        id: 'l4-s2',
        podName: 'network-tool',
        namespace: 'ops',
        verdict: 'deny',
        violatedRule: 'no-dangerous-caps',
        explanation: 'NET_ADMIN grants full control of the host network stack: rewrite routing tables, configure network interfaces, and manipulate firewall rules. A compromised container with this capability can intercept all traffic on the node and pivot to adjacent services.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: tool'),
          y('    image: gcr.io/tools/net:v1'),
          y('    securityContext:'),
          y('      capabilities:'),
          y('        add:', 'violation'),
          y('        - NET_ADMIN', 'violation'),
        ],
      },
      {
        id: 'l4-s3',
        podName: 'port-binder',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'Drops ALL capabilities and re-adds only NET_BIND_SERVICE, the standard exception for services that need to bind ports below 1024. This is the minimum-privilege pattern for web servers.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: server'),
          y('    image: gcr.io/myco/server:v2'),
          y('    securityContext:'),
          y('      capabilities:'),
          y('        drop:', 'ok'),
          y('        - ALL', 'ok'),
          y('        add:', 'ok'),
          y('        - NET_BIND_SERVICE', 'ok'),
        ],
      },
      {
        id: 'l4-s4',
        podName: 'sys-admin',
        namespace: 'ops',
        verdict: 'deny',
        violatedRule: 'no-dangerous-caps',
        explanation: 'SYS_ADMIN is the most dangerous Linux capability — it\'s nearly equivalent to full root. It allows mounting filesystems, injecting into processes, and overriding kernel security features. No workload in a shared cluster should have this.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: admin'),
          y('    image: gcr.io/ops/admin:v1'),
          y('    securityContext:'),
          y('      capabilities:'),
          y('        add:', 'violation'),
          y('        - SYS_ADMIN', 'violation'),
          y('        - NET_ADMIN', 'violation'),
        ],
      },
      {
        id: 'l4-s5',
        podName: 'app-nodrop',
        namespace: 'staging',
        verdict: 'deny',
        violatedRule: 'drop-all',
        explanation: 'No capabilities block means all default Linux capabilities are still active: CHOWN, DAC_OVERRIDE, FOWNER, SETUID, SETGID, and more. These allow the container to modify file ownership, bypass file permission checks, and impersonate other users. They must be explicitly dropped.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/myco/app:v3'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false'),
          y('      runAsNonRoot: true'),
          y('      # no capabilities block', 'violation'),
        ],
      },
      {
        id: 'l4-s6',
        podName: 'raw-proxy',
        namespace: 'network',
        verdict: 'deny',
        violatedRule: 'no-dangerous-caps',
        explanation: 'NET_RAW allows the container to craft raw packets and inject them at the network layer — enabling ARP poisoning, IP spoofing, and MITM attacks against other pods on the same node. Only NET_BIND_SERVICE may be added back.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: proxy'),
          y('    image: gcr.io/myco/proxy:v1'),
          y('    securityContext:'),
          y('      capabilities:'),
          y('        drop:', 'ok'),
          y('        - ALL', 'ok'),
          y('        add:', 'violation'),
          y('        - NET_RAW', 'violation'),
        ],
      },
      {
        id: 'l4-s7',
        podName: 'strict-app',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'Drops ALL capabilities, no re-additions, plus allowPrivilegeEscalation: false and readOnlyRootFilesystem: true. This container has near-zero attack surface even if its process is fully compromised.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/myco/app:v2'),
          y('    securityContext:'),
          y('      capabilities:'),
          y('        drop:', 'ok'),
          y('        - ALL', 'ok'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      runAsNonRoot: true', 'ok'),
          y('      readOnlyRootFilesystem: true', 'ok'),
        ],
      },
      {
        id: 'l4-s8',
        podName: 'partial-drop',
        namespace: 'ops',
        verdict: 'deny',
        violatedRule: 'drop-all',
        explanation: 'Dropping individual capabilities is not equivalent to dropping ALL. This pod drops NET_ADMIN and SYS_TIME but retains CHOWN, DAC_OVERRIDE, SETUID, and others. Policy requires drop: [ALL] as the baseline — selective drops leave too many capabilities active.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: tracer'),
          y('    image: gcr.io/ops/tracer:v1'),
          y('    securityContext:'),
          y('      capabilities:'),
          y('        drop:', 'violation'),
          y('        - NET_ADMIN', 'violation'),
          y('        - SYS_TIME', 'violation'),
          y('        # missing: - ALL', 'violation'),
        ],
      },
    ],
  },

  // ─── Level 5: Image Registry Policy ──────────────────────────────────────
  {
    id: 5,
    title: 'Approved Image Registries',
    policyName: 'POLICY-005: Supply Chain Control',
    intro:
      "Only images from gcr.io/company/ or registry.company.internal/ are permitted. " +
      "The 'latest' tag is banned — it is mutable and breaks reproducibility. " +
      "Deny anything from public registries or using latest.",
    rules: [
      {
        id: 'approved-registry',
        label: 'Approved registries only',
        description: 'Images must come from gcr.io/company/ or registry.company.internal/.',
      },
      {
        id: 'no-latest-tag',
        label: 'No latest tag',
        description: "Images may not use the 'latest' tag. All images must be pinned to a specific version.",
      },
    ],
    timeLimit: 100,
    pointsPerCorrect: 130,
    scenarios: [
      {
        id: 'l5-s1',
        podName: 'web-frontend',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'From the approved registry gcr.io/company/ with a pinned digest-equivalent version tag. This image was built, scanned, and signed by the internal pipeline. Provenance is established.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: web'),
          y('    image: gcr.io/company/nginx:1.21.6', 'ok'),
        ],
      },
      {
        id: 'l5-s2',
        podName: 'debug-pod',
        namespace: 'ops',
        verdict: 'deny',
        violatedRule: 'approved-registry',
        explanation: 'Public Docker Hub images bypass internal security scanning and signing. Any dependency in ubuntu:22.04 that has a CVE won\'t appear in your internal vulnerability reports until after it\'s already running in your cluster.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: debug'),
          y('    image: ubuntu:22.04', 'violation'),
        ],
      },
      {
        id: 'l5-s3',
        podName: 'redis-cache',
        namespace: 'production',
        verdict: 'deny',
        violatedRule: 'no-latest-tag',
        explanation: 'latest is a mutable pointer that can change on every pull. Today it\'s a patched image; tomorrow it might resolve to a version with a critical CVE. It also breaks rollback and makes incident investigation impossible — you can\'t prove what code was running.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: cache'),
          y('    image: gcr.io/company/redis:latest', 'violation'),
        ],
      },
      {
        id: 'l5-s4',
        podName: 'internal-api',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'Internal registry with a pinned version. This image went through the internal build pipeline, was vulnerability-scanned, and has immutable provenance. registry.company.internal/ is an approved source.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: api'),
          y('    image: registry.company.internal/api:v4.2.1', 'ok'),
        ],
      },
      {
        id: 'l5-s5',
        podName: 'typosquat',
        namespace: 'staging',
        verdict: 'deny',
        violatedRule: 'approved-registry',
        explanation: 'gcr.io/company-external/ looks similar to gcr.io/company/ but is a completely different Google Cloud project with no internal vetting. This is a typosquatting or supply chain confusion scenario — a subtle registry name difference with full exploit potential.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company-external/app:v1.0', 'violation'),
        ],
      },
      {
        id: 'l5-s6',
        podName: 'envoy-proxy',
        namespace: 'mesh',
        verdict: 'deny',
        violatedRule: 'approved-registry',
        explanation: 'envoyproxy/envoy is a public Docker Hub image outside the approved supply chain. No internal vulnerability scanning, no SBOM, no signature. Using it means you\'re accepting whatever security posture the upstream maintainers have — including any unpatched CVEs at time of pull.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: proxy'),
          y('    image: envoyproxy/envoy:v1.27.0', 'violation'),
        ],
      },
      {
        id: 'l5-s7',
        podName: 'batch-worker',
        namespace: 'jobs',
        verdict: 'admit',
        explanation: 'Both containers use approved registries with pinned version tags. Full supply chain traceability — you know exactly what code is running and can reproduce the exact image from internal build artifacts.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: worker'),
          y('    image: gcr.io/company/worker:3.0.1-stable', 'ok'),
          y('  - name: sidecar'),
          y('    image: registry.company.internal/sidecar:v2.1', 'ok'),
        ],
      },
      {
        id: 'l5-s8',
        podName: 'monitor-stack',
        namespace: 'monitoring',
        verdict: 'deny',
        violatedRule: 'approved-registry',
        explanation: 'The prometheus sidecar uses a public Docker Hub image with the latest tag — two violations in one container. It bypasses internal scanning and its version is non-deterministic. Every container in a pod must come from approved sources.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: monitor'),
          y('    image: gcr.io/company/monitor:v2.1', 'ok'),
          y('  - name: prometheus'),
          y('    image: prom/prometheus:latest', 'violation'),
        ],
      },
    ],
  },

  // ─── Level 6: Resource Limits Required ───────────────────────────────────
  {
    id: 6,
    title: 'Resource Limits Required',
    policyName: 'POLICY-006: Resource Quotas',
    intro:
      'Pods without resource limits can consume unbounded CPU and memory, starving other workloads and crashing nodes. ' +
      'Every container must specify both resources.limits.cpu and resources.limits.memory. ' +
      'Requests are optional; limits are mandatory.',
    rules: [
      {
        id: 'cpu-limit',
        label: 'CPU limit required',
        description: 'Every container must set resources.limits.cpu.',
      },
      {
        id: 'memory-limit',
        label: 'Memory limit required',
        description: 'Every container must set resources.limits.memory.',
      },
    ],
    timeLimit: 100,
    pointsPerCorrect: 140,
    scenarios: [
      {
        id: 'l6-s1',
        podName: 'api-server',
        namespace: 'production',
        verdict: 'deny',
        violatedRule: 'cpu-limit',
        explanation: 'Without limits, a memory leak or runaway process in this container can consume all available node memory. The kernel\'s OOM killer then starts terminating other processes on the node — not just in this pod, but potentially in unrelated, well-behaved pods sharing the same node.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: api'),
          y('    image: gcr.io/company/api:v3'),
          y('    ports:'),
          y('    - containerPort: 8080'),
          y('    # no resources defined', 'violation'),
        ],
      },
      {
        id: 'l6-s2',
        podName: 'web-frontend',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'CPU limit of 500m and memory limit of 256Mi are both set. The worst case for a misbehaving container is consuming 0.5 CPUs and 256MiB — bounded and predictable. Other pods on the node are protected.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: web'),
          y('    image: gcr.io/company/web:v2'),
          y('    resources:'),
          y('      limits:', 'ok'),
          y('        cpu: 500m', 'ok'),
          y('        memory: 256Mi', 'ok'),
        ],
      },
      {
        id: 'l6-s3',
        podName: 'worker-job',
        namespace: 'jobs',
        verdict: 'deny',
        violatedRule: 'cpu-limit',
        explanation: 'Requests reserve capacity for scheduling; limits cap consumption at runtime. Without limits, this worker can burst to consume all free CPU and memory on the node regardless of what was reserved. Requests without limits is a half-measure.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: worker'),
          y('    image: gcr.io/company/worker:v1'),
          y('    resources:'),
          y('      requests:'),
          y('        cpu: 100m'),
          y('        memory: 64Mi'),
          y('      # no limits block', 'violation'),
        ],
      },
      {
        id: 'l6-s4',
        podName: 'cache-pod',
        namespace: 'data',
        verdict: 'deny',
        violatedRule: 'cpu-limit',
        explanation: 'Memory limit is set but the CPU limit is missing. An unbounded CPU consumer can starve other pods\' CPU allocations and trigger throttling cluster-wide. Both limits are required — one without the other leaves a gap.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: cache'),
          y('    image: gcr.io/company/redis:v7'),
          y('    resources:'),
          y('      limits:', 'neutral'),
          y('        memory: 512Mi', 'ok'),
          y('        # cpu limit missing', 'violation'),
        ],
      },
      {
        id: 'l6-s5',
        podName: 'batch-job',
        namespace: 'jobs',
        verdict: 'admit',
        explanation: 'Requests reserve capacity at scheduling time; limits enforce the ceiling at runtime. Both are set for CPU and memory. This container\'s resource consumption is fully bounded and predictable.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: batch'),
          y('    image: gcr.io/company/batch:v4'),
          y('    resources:'),
          y('      requests:'),
          y('        cpu: 250m'),
          y('        memory: 128Mi'),
          y('      limits:', 'ok'),
          y('        cpu: "1"', 'ok'),
          y('        memory: 512Mi', 'ok'),
        ],
      },
      {
        id: 'l6-s6',
        podName: 'app-with-sidecar',
        namespace: 'production',
        verdict: 'deny',
        violatedRule: 'cpu-limit',
        explanation: 'The main app container is correctly limited, but the logger sidecar has no limits. A logging agent with an infinite loop or a backed-up write buffer can consume all remaining node memory. Every container in the pod must be bounded.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v2'),
          y('    resources:'),
          y('      limits:', 'ok'),
          y('        cpu: 500m', 'ok'),
          y('        memory: 256Mi', 'ok'),
          y('  - name: logger'),
          y('    image: gcr.io/company/logger:v1'),
          y('    # no resources defined', 'violation'),
        ],
      },
      {
        id: 'l6-s7',
        podName: 'scanner',
        namespace: 'security',
        verdict: 'admit',
        explanation: 'Both containers have explicit CPU and memory limits. The total worst-case resource consumption for this pod is calculable and bounded. The node cannot be overwhelmed by either container alone.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: scanner'),
          y('    image: gcr.io/company/scanner:v3'),
          y('    resources:'),
          y('      limits:', 'ok'),
          y('        cpu: 200m', 'ok'),
          y('        memory: 128Mi', 'ok'),
          y('  - name: reporter'),
          y('    image: gcr.io/company/reporter:v1'),
          y('    resources:'),
          y('      limits:', 'ok'),
          y('        cpu: 100m', 'ok'),
          y('        memory: 64Mi', 'ok'),
        ],
      },
      {
        id: 'l6-s8',
        podName: 'data-agent',
        namespace: 'data',
        verdict: 'deny',
        violatedRule: 'memory-limit',
        explanation: 'CPU limit is set but memory limit is missing. A container without a memory limit can trigger the node-level OOM killer, which terminates processes across the entire node — including pods from completely unrelated deployments.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: agent'),
          y('    image: gcr.io/company/agent:v2'),
          y('    resources:'),
          y('      limits:', 'neutral'),
          y('        cpu: 200m', 'ok'),
          y('        # memory limit missing', 'violation'),
        ],
      },
    ],
  },

  // ─── Level 7: Allow Privilege Escalation ─────────────────────────────────
  {
    id: 7,
    title: 'Block Privilege Escalation',
    policyName: 'POLICY-007: No Setuid Escalation',
    intro:
      'In Kubernetes, allowPrivilegeEscalation defaults to true. This means setuid/setgid binaries ' +
      'inside a container can silently gain elevated privileges. ' +
      'Every container must explicitly set allowPrivilegeEscalation: false. ' +
      'Missing the field means deny — defaults are not safe.',
    rules: [
      {
        id: 'no-privilege-escalation',
        label: 'allowPrivilegeEscalation: false',
        description: 'Every container must explicitly set securityContext.allowPrivilegeEscalation: false.',
      },
    ],
    timeLimit: 90,
    pointsPerCorrect: 150,
    scenarios: [
      {
        id: 'l7-s1',
        podName: 'app-no-field',
        namespace: 'production',
        verdict: 'deny',
        violatedRule: 'no-privilege-escalation',
        explanation: 'allowPrivilegeEscalation defaults to true in Kubernetes. If this container runs any binary with the setuid or setgid bit set, that process gains elevated privileges at runtime — silently, with no audit trail. It must be explicitly set to false.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v1'),
          y('    securityContext:'),
          y('      runAsNonRoot: true'),
          y('      # allowPrivilegeEscalation not set → defaults to true', 'violation'),
        ],
      },
      {
        id: 'l7-s2',
        podName: 'secure-app',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'allowPrivilegeEscalation: false prevents any process inside this container from gaining more privileges than the container started with. Even if an attacker plants a setuid binary, it won\'t escalate.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v2'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      runAsNonRoot: true', 'ok'),
        ],
      },
      {
        id: 'l7-s3',
        podName: 'old-service',
        namespace: 'legacy',
        verdict: 'deny',
        violatedRule: 'no-privilege-escalation',
        explanation: 'allowPrivilegeEscalation: true explicitly enables setuid/setgid privilege escalation inside the container. If an attacker can write a setuid binary or trigger an existing one, they gain elevated privileges within the container — a stepping stone to host compromise.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: service'),
          y('    image: gcr.io/company/service:v0.9'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: true', 'violation'),
        ],
      },
      {
        id: 'l7-s4',
        podName: 'hardened-worker',
        namespace: 'jobs',
        verdict: 'admit',
        explanation: 'allowPrivilegeEscalation: false with drop: [ALL], runAsUser: 1000, and readOnlyRootFilesystem: true. An attacker who compromises this container\'s process cannot escalate privileges, cannot drop capabilities back in, and cannot write malicious binaries to disk.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: worker'),
          y('    image: gcr.io/company/worker:v3'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      runAsUser: 1000', 'ok'),
          y('      readOnlyRootFilesystem: true', 'ok'),
          y('      capabilities:'),
          y('        drop:'),
          y('        - ALL', 'ok'),
        ],
      },
      {
        id: 'l7-s5',
        podName: 'partial-config',
        namespace: 'staging',
        verdict: 'deny',
        violatedRule: 'no-privilege-escalation',
        explanation: 'The main app container is correctly locked down, but the sidecar doesn\'t set allowPrivilegeEscalation. The field defaults to true. An attacker who pivots from the app to the sidecar gets a process that can escalate — the hardening of one container doesn\'t protect the other.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v2'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('  - name: sidecar'),
          y('    image: gcr.io/company/sidecar:v1'),
          y('    securityContext:'),
          y('      runAsNonRoot: true'),
          y('      # allowPrivilegeEscalation not set', 'violation'),
        ],
      },
      {
        id: 'l7-s6',
        podName: 'two-containers',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'Both containers explicitly set allowPrivilegeEscalation: false. Neither can gain privileges via setuid/setgid binaries. The entire pod\'s attack surface is bounded.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v3'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('  - name: proxy'),
          y('    image: gcr.io/company/proxy:v1'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
        ],
      },
      {
        id: 'l7-s7',
        podName: 'init-escalation',
        namespace: 'data',
        verdict: 'deny',
        violatedRule: 'no-privilege-escalation',
        explanation: 'The init container doesn\'t set allowPrivilegeEscalation — it defaults to true. Init containers run database migrations, filesystem setup, and other sensitive operations before your app starts. A privileged init phase with the ability to escalate can silently compromise the environment the main container inherits.',
        yaml: [
          y('spec:'),
          y('  initContainers:'),
          y('  - name: init-schema'),
          y('    image: gcr.io/company/migrator:v2'),
          y('    securityContext:'),
          y('      runAsUser: 999'),
          y('      # allowPrivilegeEscalation not set', 'violation'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v4'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
        ],
      },
      {
        id: 'l7-s8',
        podName: 'fully-locked',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'Both the init container and the main container explicitly set allowPrivilegeEscalation: false. The full pod lifecycle — from init to runtime — is hardened against privilege escalation.',
        yaml: [
          y('spec:'),
          y('  initContainers:'),
          y('  - name: init'),
          y('    image: gcr.io/company/init:v1'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v5'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      runAsNonRoot: true', 'ok'),
        ],
      },
    ],
  },

  // ─── Level 8: PSA Restricted (Combined) ──────────────────────────────────
  {
    id: 8,
    title: 'PSA Restricted — Combined Policy',
    policyName: 'POLICY-FINAL: Pod Security Admission (Restricted)',
    intro:
      'The full Kubernetes Pod Security Admission "restricted" profile is now in effect. ' +
      'All previous rules apply simultaneously. One violation from any rule means deny. ' +
      'Read carefully — some pods are almost compliant but fail on a single field.',
    rules: [
      { id: 'no-privileged', label: 'No privileged', description: 'No container may set privileged: true.' },
      { id: 'no-host-ns', label: 'No host namespaces', description: 'No hostPID, hostIPC, or hostNetwork.' },
      { id: 'run-as-non-root', label: 'Non-root required', description: 'All containers must run as non-root.' },
      { id: 'drop-all', label: 'Drop ALL caps', description: 'All containers must drop ALL capabilities.' },
      { id: 'no-priv-esc', label: 'No privilege escalation', description: 'allowPrivilegeEscalation: false on all containers.' },
      { id: 'resource-limits', label: 'Resource limits', description: 'All containers must set CPU and memory limits.' },
    ],
    timeLimit: 90,
    pointsPerCorrect: 200,
    scenarios: [
      {
        id: 'l8-s1',
        podName: 'fully-compliant',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'Fully compliant with PSA restricted: non-root user, drop ALL capabilities, allowPrivilegeEscalation: false, and resource limits. If this container is compromised, the attacker is unprivileged, capability-less, and resource-bounded.',
        yaml: [
          y('spec:'),
          y('  securityContext:'),
          y('    runAsNonRoot: true', 'ok'),
          y('    runAsUser: 1000', 'ok'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v5.1'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      capabilities:'),
          y('        drop: [ALL]', 'ok'),
          y('    resources:'),
          y('      limits:', 'ok'),
          y('        cpu: 500m', 'ok'),
          y('        memory: 256Mi', 'ok'),
        ],
      },
      {
        id: 'l8-s2',
        podName: 'missing-non-root',
        namespace: 'staging',
        verdict: 'deny',
        violatedRule: 'run-as-non-root',
        explanation: 'Every other field is correctly configured, but runAsNonRoot is not set — the container may run as root. PSA restricted requires non-root enforcement. A single missing field fails the entire pod.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v3'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      capabilities:'),
          y('        drop: [ALL]', 'ok'),
          y('      # runAsNonRoot not set', 'violation'),
          y('    resources:'),
          y('      limits:'),
          y('        cpu: 250m'),
          y('        memory: 128Mi'),
        ],
      },
      {
        id: 'l8-s3',
        podName: 'privileged-pod',
        namespace: 'ops',
        verdict: 'deny',
        violatedRule: 'no-privileged',
        explanation: 'privileged: true immediately fails PSA restricted. This field alone gives near-root host access — all other security context hardening is irrelevant once privileged mode is active.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: tool'),
          y('    image: gcr.io/company/tool:v1'),
          y('    securityContext:'),
          y('      privileged: true', 'violation'),
          y('      allowPrivilegeEscalation: false'),
          y('      runAsUser: 1000'),
          y('      capabilities:'),
          y('        drop: [ALL]'),
        ],
      },
      {
        id: 'l8-s4',
        podName: 'golden-pod',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'Full PSA restricted compliance: no host namespaces, non-root execution, all capabilities dropped, no privilege escalation, and resource limits. A model production pod.',
        yaml: [
          y('spec:'),
          y('  hostPID: false', 'ok'),
          y('  hostNetwork: false', 'ok'),
          y('  securityContext:'),
          y('    runAsNonRoot: true', 'ok'),
          y('    runAsUser: 999', 'ok'),
          y('  containers:'),
          y('  - name: service'),
          y('    image: registry.company.internal/svc:v2.0'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      capabilities: { drop: [ALL] }', 'ok'),
          y('    resources: { limits: { cpu: 200m, memory: 128Mi } }', 'ok'),
        ],
      },
      {
        id: 'l8-s5',
        podName: 'multi-violation',
        namespace: 'legacy',
        verdict: 'deny',
        violatedRule: 'drop-all',
        explanation: 'Multiple violations: root user (runAsUser: 0), no capabilities drop, no allowPrivilegeEscalation. This legacy workload has an unrestricted attack surface. A compromise means full container privilege, with Linux capabilities intact and a path to the host.',
        yaml: [
          y('spec:'),
          y('  containers:'),
          y('  - name: legacy-app'),
          y('    image: gcr.io/company/legacy:v0.5'),
          y('    securityContext:'),
          y('      runAsUser: 0', 'violation'),
          y('      # no capabilities drop', 'violation'),
          y('      # no allowPrivilegeEscalation', 'violation'),
          y('    resources:'),
          y('      limits:'),
          y('        cpu: 1'),
          y('        memory: 1Gi'),
        ],
      },
      {
        id: 'l8-s6',
        podName: 'host-network-app',
        namespace: 'network',
        verdict: 'deny',
        violatedRule: 'no-host-ns',
        explanation: 'hostNetwork: true violates PSA restricted. Even though every other field is locked down, this single setting removes pod-level network isolation and allows the pod to see all host traffic. One violation fails the whole pod under the combined policy.',
        yaml: [
          y('spec:'),
          y('  hostNetwork: true', 'violation'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v4'),
          y('    securityContext:'),
          y('      runAsUser: 1000', 'ok'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      capabilities: { drop: [ALL] }', 'ok'),
          y('    resources: { limits: { cpu: 200m, memory: 64Mi } }', 'ok'),
        ],
      },
      {
        id: 'l8-s7',
        podName: 'multi-container-ok',
        namespace: 'production',
        verdict: 'admit',
        explanation: 'Both containers satisfy every PSA restricted requirement: non-root, drop ALL capabilities, no privilege escalation, and resource limits. Each container\'s blast radius is independently bounded.',
        yaml: [
          y('spec:'),
          y('  securityContext: { runAsNonRoot: true, runAsUser: 1000 }', 'ok'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v6'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      capabilities: { drop: [ALL] }', 'ok'),
          y('    resources: { limits: { cpu: 500m, memory: 256Mi } }', 'ok'),
          y('  - name: proxy'),
          y('    image: gcr.io/company/proxy:v3'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      capabilities: { drop: [ALL] }', 'ok'),
          y('    resources: { limits: { cpu: 100m, memory: 64Mi } }', 'ok'),
        ],
      },
      {
        id: 'l8-s8',
        podName: 'almost-there',
        namespace: 'staging',
        verdict: 'deny',
        violatedRule: 'resource-limits',
        explanation: 'The sidecar container is missing resource limits. Under PSA restricted, every container must be bounded. An unbounded sidecar — even a small logging agent — can trigger OOM conditions that kill the entire node\'s workload.',
        yaml: [
          y('spec:'),
          y('  securityContext: { runAsNonRoot: true, runAsUser: 500 }', 'ok'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v5'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      capabilities: { drop: [ALL] }', 'ok'),
          y('    resources: { limits: { cpu: 250m, memory: 128Mi } }', 'ok'),
          y('  - name: sidecar'),
          y('    image: gcr.io/company/sidecar:v2'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      capabilities: { drop: [ALL] }', 'ok'),
          y('    # no resources defined', 'violation'),
        ],
      },
      {
        id: 'l8-s9',
        podName: 'priv-esc-slip',
        namespace: 'production',
        verdict: 'deny',
        violatedRule: 'no-priv-esc',
        explanation: 'allowPrivilegeEscalation is not set — it defaults to true. Every other PSA restricted requirement is met, but this one omission means a setuid binary in this container can escalate to elevated privileges silently. One field. Full policy failure.',
        yaml: [
          y('spec:'),
          y('  securityContext: { runAsNonRoot: true, runAsUser: 1000 }', 'ok'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: gcr.io/company/app:v7'),
          y('    securityContext:'),
          y('      capabilities: { drop: [ALL] }', 'ok'),
          y('      # allowPrivilegeEscalation not set', 'violation'),
          y('    resources: { limits: { cpu: 200m, memory: 128Mi } }', 'ok'),
        ],
      },
      {
        id: 'l8-s10',
        podName: 'textbook-pod',
        namespace: 'production',
        verdict: 'admit',
        explanation: "Textbook PSA restricted compliance: non-root UID with seccompProfile (limits syscalls), drop ALL capabilities, allowPrivilegeEscalation: false, readOnlyRootFilesystem, and resource limits. The complete defense-in-depth stack.",
        yaml: [
          y('spec:'),
          y('  securityContext:'),
          y('    runAsNonRoot: true', 'ok'),
          y('    runAsUser: 10001', 'ok'),
          y('    seccompProfile: { type: RuntimeDefault }', 'ok'),
          y('  containers:'),
          y('  - name: app'),
          y('    image: registry.company.internal/app:v8.0.2'),
          y('    securityContext:'),
          y('      allowPrivilegeEscalation: false', 'ok'),
          y('      readOnlyRootFilesystem: true', 'ok'),
          y('      capabilities: { drop: [ALL] }', 'ok'),
          y('    resources: { limits: { cpu: 500m, memory: 256Mi } }', 'ok'),
        ],
      },
    ],
  },
];

export function getLevelConfig(levelId: number): LevelConfig | undefined {
  return LEVELS.find((l) => l.id === levelId);
}

export const TOTAL_LEVELS = LEVELS.length;
